apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-app
  namespace: observability-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: observability-app
  template:
    metadata:
      labels:
        app: observability-app
    spec:
      containers:
        - name: observability-app
          image: yaswanthsuram/kubernetes-observability-app:latest
          ports:
            - containerPort: 5000
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 20
