apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observability-app
  namespace: observability-demo
spec:
  selector:
    matchLabels:
      app: observability-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
