apiVersion: v1
kind: Service
metadata:
  name: observability-app
  namespace: observability-demo
  labels:
    app: observability-app
spec:
  selector:
    app: observability-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
